version: '3.9'
services:
  # spring_app:
  #   container_name: candlelight_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongodb 
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_DATASOURCE_DB=candlelight
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=changemeinprod!
  #     - SPRING_DATASOURCE_HOST=mongodb 
  #     - SPRING_DATASOURCE_PORT=27017
  #   networks:
  #     - candlelight

  mongodb:
    image: mongo
    container_name: candlelight_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=candlelight
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changemeinprod!
    volumes:
      - mongo:/data
    networks:
      - candlelight
  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=changemeinprod!
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - candlelight

volumes:
  mongo: {}

networks:
  candlelight:
    driver: bridge